info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: https://keycloak-edp-cockpit-demo.demo-cluster.edp-epam.com/auth
  realm: foobar-realm
  resource: foobar-client
  ssl-required: NONE
  credentials:
    secret: secret

zuul:
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
    bar-service:
      path: /bar/**
      service-id: bar-service