info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

zuul:
  sensitiveHeaders:
  routes:
    example:
      path: /example/**
      serviceId: example

example:
  ribbon:
    listOfServers: example:8080