info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: http://ec2-18-185-211-132.eu-central-1.compute.amazonaws.com:31969/auth
  realm: foobar-realm-sit
  resource: foobar-client
  credentials:
    secret: fc4a02d1-c80b-4bac-ac03-a5d92a453e87

zuul:
  sensitiveHeaders:
  routes:
    foo:
      path: /foo/**
      serviceId: foo
    bar:
      path: /bar/**
      serviceId: bar

foo:
  ribbon:
    listOfServers: foo-service:8080
bar:
  ribbon:
    listOfServers: bar-service:8080