info:
  component: Zuul Server

server:
  port: ${apigateway-port}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

zuul:
  routes:
    cart-service:
      path: /cart-service/**
      service-id: cart-service
    order-service:
      path: /order-service/**
      service-id: order-service

order-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 0
    OkToRetryOnAllOperations: true
    ReadTimeout: 5000

cart-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 0
    OkToRetryOnAllOperations: true
    ReadTimeout: 5000

---
spring:
  profiles: local
  cloud:
    kubernetes:
      ribbon:
        enabled: false

order-service:
  ribbon:
    listOfServers: https://order-service-gk-grace-master-dev.dev.gk-edp.com

cart-service:
  ribbon:
    listOfServers: https://cart-service-gk-grace-master-dev.dev.gk-edp.com