info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: https://keycloak-sit-demo.demo-cluster.edp-epam.com/auth
  realm: foobar
  resource: foobar
  public-client: true

zuul:
  sensitiveHeaders:
  routes:
    foo:
      path: /api/foo/**
      serviceId: foo
    bar:
      path: /api/bar/**
      serviceId: bar

foo:
  ribbon:
    listOfServers: foo:8080
bar:
  ribbon:
    listOfServers: bar:8080