info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

zuul:
  routes:
    cart-service:
      path: /cart-service/**
      service-id: cart-service
    order-service:
      path: /order-service/**
      service-id: order-service