info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: http://ec2-18-185-211-132.eu-central-1.compute.amazonaws.com:31972/auth
  realm: foobar
  resource: foobar
  credentials:
    secret: secret

zuul:
  sensitiveHeaders:
  routes:
    foo:
      path: /foo/**
      serviceId: foo
    bar:
      path: /bar/**
      serviceId: bar

foo:
  ribbon:
    listOfServers: foo:8080
bar:
  ribbon:
    listOfServers: bar:8080