info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: http://ec2-18-185-211-132.eu-central-1.compute.amazonaws.com:31969/auth
  realm: foobar-realm
  resource: foobar-client
  credentials:
    secret: secret

zuul:
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
    bar-service:
      path: /bar/**
      service-id: bar-service

bar-service:
  ribbon:
    NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
    Namespace: sit-demo
    PortName: bar-service

foo-service:
  ribbon:
    NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
    Namespace: sit-demo
    PortName: foo-service