info:
  component: Zuul Server

server:
  port: ${apigateway-port}
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

keycloak:
  auth-server-url: http://ec2-18-185-211-132.eu-central-1.compute.amazonaws.com:31969/auth
  realm: foobar-realm
  resource: foobar-client
  credentials:
    secret: secret